[package]
name = "cirrus-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aiff = {git = "https://github.com/julientregoat/aiff-rs.git"}
quinn = "0.8.1"