[package]
name = "cirrus-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"
futures = "0.3"
h3 = { git = "https://github.com/hyperium/h3" }
h3-quinn = { git = "https://github.com/hyperium/h3" }
http = "0.2"
rcgen = "0.9.1"
rustls = { version = "0.20", features = ["dangerous_configuration"] }
rustls-native-certs = "0.6"
tokio = { version = "1", features = ["full"] }
